"""hermesbench/report.py — standalone HTML report generator."""

from __future__ import annotations

import html
from datetime import datetime
from pathlib import Path


def generate_html_report(results: list[dict], out_path: str, model_name: str = "") -> None:
    """Generate a dark-themed HTML report with pass/fail tables."""
    total = len(results)
    passed = sum(1 for r in results if r.get("status") == "PASS")
    rate = passed / total * 100 if total else 0

    cats: dict[str, dict[str, int]] = {}
    for r in results:
        cat = r["task_id"].rsplit("/", 1)[0]
        cats.setdefault(cat, {"pass": 0, "total": 0})
        cats[cat]["total"] += 1
        if r.get("status") == "PASS":
            cats[cat]["pass"] += 1

    task_rows = []
    for r in sorted(results, key=lambda x: x.get("task_id", "")):
        status = r.get("status", "UNKNOWN")
        color = "#4ecb71" if status == "PASS" else "#f05050"
        reason = html.escape(r.get("reason", ""))[:100]
        task_rows.append(
            f"<tr><td>{html.escape(r.get('task_id', ''))}</td>"
            f'<td style="color:{color}">{status}</td>'
            f'<td style="color:#888;text-align:left">{reason}</td></tr>'
        )

    cat_rows = []
    for cat in sorted(cats):
        p = cats[cat]["pass"]
        t = cats[cat]["total"]
        pct = p / t * 100 if t else 0
        cat_rows.append(f"<tr><td>{html.escape(cat)}</td><td>{p}/{t}</td><td>{pct:.0f}%</td></tr>")

    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    doc = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>HermesBench Results — {html.escape(model_name)}</title>
<style>
:root {{--bg:#1a1a2e;--card:#252540;--text:#e0e0e8;--accent:#7c8cf8;--green:#4ecb71;--red:#f05050}}
*{{margin:0;padding:0;box-sizing:border-box}}
body{{background:var(--bg);color:var(--text);font-family:monospace;padding:20px;max-width:900px;margin:0 auto}}
h1{{color:var(--accent);margin:16px 0}}
h2{{color:var(--accent);margin:20px 0 8px;border-bottom:1px solid #333;padding-bottom:4px}}
.card{{background:var(--card);border-radius:8px;padding:16px;margin:12px 0}}
table{{width:100%;border-collapse:collapse;font-size:.9rem}}
th,td{{padding:6px 10px;text-align:left;border-bottom:1px solid #333}}
th{{background:#2a2a40}}
.big{{font-size:2rem;font-weight:bold;color:var(--accent)}}
</style></head><body>
<h1>HermesBench v0.2 — {html.escape(model_name)}</h1>
<div class="card"><div class="big">{rate:.1f}%</div>
<div>{passed}/{total} tasks passed · {now}</div></div>
<h2>By Category</h2>
<div class="card"><table><tr><th>Category</th><th>Pass/Total</th><th>Rate</th></tr>
{"".join(cat_rows)}</table></div>
<h2>Per-Task Detail</h2>
<div class="card" style="max-height:500px;overflow-y:auto"><table>
<tr><th>Task ID</th><th>Status</th><th>Reason</th></tr>
{"".join(task_rows)}</table></div>
<p style="text-align:center;margin:20px 0;color:#666;font-size:.8rem">
Generated by HermesBench v0.2</p>
</body></html>"""
    Path(out_path).write_text(doc)


def generate_comparison_html(results: dict[str, list[dict]], out_path: str) -> None:
    """Side-by-side HTML comparison of multiple model runs."""
    all_cats: set[str] = set()
    summaries: dict[str, dict] = {}
    for run_path, res in results.items():
        label = Path(run_path).name
        total = len(res)
        passed = sum(1 for r in res if r.get("status") == "PASS")
        cats: dict[str, list[int]] = {}
        for r in res:
            cat = r["task_id"].rsplit("/", 1)[0]
            cats.setdefault(cat, [0, 0])
            cats[cat][1] += 1
            if r.get("status") == "PASS":
                cats[cat][0] += 1
        summaries[label] = {"total": total, "passed": passed, "cats": cats}
        all_cats.update(cats.keys())

    labels = list(summaries.keys())
    header = (
        "<tr><th>Category</th>"
        + "".join(f"<th>{html.escape(label)}</th>" for label in labels)
        + "</tr>"
    )
    rows = []
    row = "<td><b>Overall</b></td>"
    for label in labels:
        s = summaries[label]
        pct = s["passed"] / s["total"] * 100 if s["total"] else 0
        row += f"<td><b>{s['passed']}/{s['total']} ({pct:.0f}%)</b></td>"
    rows.append(f"<tr>{row}</tr>")
    for cat in sorted(all_cats):
        row = f"<td>{html.escape(cat)}</td>"
        for label in labels:
            p, t = summaries[label]["cats"].get(cat, (0, 0))
            row += f"<td>{p}/{t}</td>" if t else "<td>-</td>"
        rows.append(f"<tr>{row}</tr>")

    doc = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>HermesBench Model Comparison</title>
<style>
:root{{--bg:#1a1a2e;--card:#252540;--text:#e0e0e8;--accent:#7c8cf8}}
*{{margin:0;padding:0;box-sizing:border-box}}
body{{background:var(--bg);color:var(--text);font-family:monospace;padding:20px;max-width:900px;margin:0 auto}}
h1{{color:var(--accent);margin:16px 0}}
.card{{background:var(--card);border-radius:8px;padding:16px;margin:12px 0;overflow-x:auto}}
table{{width:100%;border-collapse:collapse;font-size:.9rem}}
th,td{{padding:6px 10px;text-align:center;border-bottom:1px solid #333}}
th{{background:#2a2a40}}
td:first-child,th:first-child{{text-align:left}}
</style></head><body>
<h1>Model Comparison</h1>
<div class="card"><table>{header}{"".join(rows)}</table></div>
</body></html>"""
    Path(out_path).write_text(doc)
